#!/usr/bin/env python3

import rospy
from dnn_controller import DNNNavigationNode

if __name__ == '__main__':
    # Initialize objects
    rospy.init_node('dnn_navigation')
    dn = DNNNavigationNode()
    rospy.spin()
