#!/usr/bin/env python3

import rospy
from pure_pursuit import PurePursuitNode

if __name__ == '__main__':
    # Initialize objects
    rospy.init_node('pure_pursuit')
    pp = PurePursuitNode()
    rospy.spin()
