types:
  - {id: "scarab", xdim: 0.05, ydim: 0.05, zdim: 0.5}

models:
  - {id: "/scarab40/base", type: "scarab"}
  - {id: "/scarab41/base", type: "scarab"}
  - {id: "/scarab42/base", type: "scarab"}
  - {id: "/scarab43/base", type: "scarab"}
  - {id: "/scarab44/base", type: "scarab"}
  - {id: "/scarab45/base", type: "scarab"}
