#!/usr/bin/env python3

import rospy
from occupancy_grid import OccupancyGridNode

if __name__ == '__main__':
    try:
        OccupancyGridNode()
    except rospy.ROSInterruptException:
        pass
